
import { NextResponse } from 'next/server'
import { supabaseAdmin } from '@/lib/supabaseAdmin'
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib'
import { v4 as uuidv4 } from 'uuid'

// Standard page sizes in points (1 pt = 1/72 inch)
const PAGE_SIZES = {
    A4: [595.28, 841.89],
    Letter: [612, 792]
}

export async function POST(req: Request) {
    try {
        const body = await req.json()
        const {
            snapshotIds,
            includeAnnotations = true,
            pageSize = 'A4',
            modelId
        }: {
            snapshotIds: string[],
            includeAnnotations: boolean,
            pageSize: 'A4' | 'Letter',
            modelId: string
        } = body

        if (!snapshotIds || snapshotIds.length === 0) {
            return NextResponse.json({ error: 'No snapshots provided' }, { status: 400 })
        }

        // 1. Fetch Metadata
        const { data: snapshots, error: snapError } = await supabaseAdmin
            .from('snapshots')
            .select(`
                *,
                snapshot_annotations (
                    u, v,
                    annotations ( text )
                )
            `)
            .in('id', snapshotIds)

        if (snapError || !snapshots) {
            console.error(snapError)
            return NextResponse.json({ error: 'Failed to fetch snapshots' }, { status: 500 })
        }

        // 2. Initialize PDF
        const pdfDoc = await PDFDocument.create()
        const font = await pdfDoc.embedFont(StandardFonts.Helvetica)
        const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
        const [pageWidth, pageHeight] = PAGE_SIZES[pageSize as keyof typeof PAGE_SIZES] || PAGE_SIZES.A4

        // 3. Process Snapshots
        for (const snap of snapshots) {
            const page = pdfDoc.addPage([pageWidth, pageHeight])

            // Download Image
            const { data: imgData, error: imgError } = await supabaseAdmin.storage
                .from('snapshots')
                .download(snap.file_key)

            if (imgError || !imgData) {
                console.error(`Failed to download ${snap.file_key}`, imgError)
                page.drawText(`Error loading image for snapshot ${snap.id}`, { x: 50, y: pageHeight - 100 })
                continue
            }

            // Embed Image
            const imgBuffer = await imgData.arrayBuffer()
            const image = await pdfDoc.embedPng(imgBuffer)

            // Fit image to page (maintain aspect ratio)
            const margin = 50
            const maxImgWidth = pageWidth - (margin * 2)
            const maxImgHeight = pageHeight - 300 // Reserve space for text
            const imgDims = image.scaleToFit(maxImgWidth, maxImgHeight)

            // Draw Image Centered
            page.drawImage(image, {
                x: (pageWidth - imgDims.width) / 2,
                y: pageHeight - margin - imgDims.height,
                width: imgDims.width,
                height: imgDims.height,
            })

            // Draw Annotation Captions
            let textY = pageHeight - margin - imgDims.height - 30

            page.drawText(`Snapshot: ${snap.id}`, {
                x: margin,
                y: textY,
                size: 14,
                font: fontBold,
                color: rgb(0, 0, 0),
            })
            textY -= 20

            if (includeAnnotations && snap.snapshot_annotations) {
                for (const ann of snap.snapshot_annotations) {
                    const text = ann.annotations?.text || 'No text'
                    page.drawText(`• ${text}`, {
                        x: margin + 10,
                        y: textY,
                        size: 10,
                        font,
                        color: rgb(0.2, 0.2, 0.2),
                    })
                    textY -= 15
                }
            }

            // Footer Metadata
            const footerText = `Generated by CAD Viewer | Model: ${modelId || 'Unknown'} | ${new Date().toISOString()}`
            page.drawText(footerText, {
                x: margin,
                y: 20,
                size: 8,
                font,
                color: rgb(0.5, 0.5, 0.5),
            })
        }

        // 4. Save and Upload PDF
        const pdfBytes = await pdfDoc.save()
        const fileName = `${modelId || 'export'}/${uuidv4()}.pdf`

        const { error: uploadError } = await supabaseAdmin.storage
            .from('exports') // Ensure 'exports' bucket exists
            .upload(fileName, pdfBytes, {
                contentType: 'application/pdf',
                upsert: false
            })

        if (uploadError) {
            console.error('Upload PDF Error:', uploadError)
            return NextResponse.json({ error: 'Failed to upload PDF' }, { status: 500 })
        }

        const { data: publicUrlData } = supabaseAdmin.storage
            .from('exports')
            .getPublicUrl(fileName)

        return NextResponse.json({
            success: true,
            url: publicUrlData.publicUrl,
            file_key: fileName
        })

    } catch (error: any) {
        console.error('Export Error:', error)
        return NextResponse.json({ error: error.message }, { status: 500 })
    }
}
